### ISSUE TITLE
Displays under the same line of the bus both origin and destination

### ISSUE THREAD

**Issue by davidss20** [silentbil/silent-bus#1]
I inserted the following station with these lines to the card :
```
type: custom: silent-bus
station: 61328
busLines:
   - 132
   - 139
```
And I get both a destination and an outlet for each line.

![Screenshot 2023-04-30 101028](https://user-images.githubusercontent.com/8984501/235340978-0a516cc1-d21c-49c8-b20f-92bee726a3d1.png)

**Comment by silentbil** [comment]
@davidss20 
Are you sure this station has only 1 way? can u tell me which of the 139 is the correct one?

also, for line 132
its looks like its the same line to 2 different places?
![image](https://user-images.githubusercontent.com/10948399/235372620-05d8553a-fd18-4d53-b909-9970b2250200.png)

**Comment by davidss20** [comment]
1.  132 Twice a day continues to Malha Mall

**Comment by silentbil** [comment]
> 1. 132 Twice a day continues to Malha Mall

so which one of the 139 is the correct? Jeruslaem or givat zeev?

**Comment by davidss20** [comment]
Jeruslaem .

**Comment by silentbil** [comment]
@davidss20 fixed
plz update to version 1.06
and let me know
