### ISSUE TITLE
Please fix it... 

### ISSUE THREAD

**Issue by MDV85** [silentbil/silent-bus#11]
![ScreenShot01 Aug  11 07 32](https://github.com/user-attachments/assets/d50def87-fab1-4b61-81bd-45fde51c6a59)
![ScreenShot02 Aug  11 07 32](https://github.com/user-attachments/assets/1644e115-8387-49f2-8609-6695d9287763)
![ScreenShot03 Aug  11 07 33](https://github.com/user-attachments/assets/fb46220e-e5b2-4600-ba23-84099645f9e3)

**Comment by silentbil** [comment]
Will fix soon

**Comment by silentbil** [comment]
i fixed, let me know if its ok now
