### ISSUE TITLE
Not getting updates

### ISSUE THREAD

**Issue by Gugulator** [silentbil/silent-bus#4]
![image](https://github.com/silentbil/silent-bus/assets/93097630/3df798eb-d236-47d4-bc8a-e96253c8ca61)
About 2-3 days before I stopped to get information for 2 cards on different bus stations.
When opening same card from mobile phone not connected to my home network, it displays correctly and working.
Is it possible that my ip was kind of banned by the service due to big number of requests?

**Comment by silentbil** [comment]
maybe, u can open the console and see the network request to see what was t he response

**Comment by Gugulator** [comment]
> maybe, u can open the console and see the network request to see what was t he response

which command i should use to see network request?

**Comment by silentbil** [comment]
chrome? f12 or right click and inspect.
then, network tab

**Comment by Gugulator** [comment]
thank you.
looks like some local problem.
can't resolve remote IP of app.busnearby.co.il
