### ISSUE TITLE
No trains data

### ISSUE THREAD

**Issue by liorpapir** [silentbil/silent-bus#5]
Hi,

Thanks for a great integration :)
After updating, I've configured trains but the card show no data.
Here's how I configured (Hod Hasharon to Savidor TLV):

type: custom:silent-bus
isTrain: true
fromStation: 17100
toStation: 17038

But the card is empty: 
<img width="419" alt="image" src="https://github.com/silentbil/silent-bus/assets/4362255/a8fdcbd2-7596-417c-885b-94d634e03289">

Thanks!

**Comment by silentbil** [comment]
Hi, i had a bug and i fixed it today.
2 options
1. Dont do anything, tomorrow it will be ok.
2. Clean localstorage if u know how
Either way, tomorrow should be find
