### ISSUE TITLE
Israel only? Then please indicate so

### ISSUE THREAD

**Issue by jensjep** [silentbil/silent-bus#7]
Hi,
This looks great 👍
Is it Israel only, or some other specific geographic area? Then please indicate that in a prominent place, such as in the title (e.g. "Bus card for Israel for homeassistant") or the small description shown in the HACS card, so the rest of the world can skip this title in HACS immediately instead of trying to figure it out from the code or the examples.
Thanks, and keep up the good work!
br Jens

**Comment by msj33** [comment]
Please Rename this addon, so its clear to the community that it is Israeli/limited localization!

**Comment by silentbil** [comment]
Hi,
thanks for the feedback
i added Israel to description
![image](https://github.com/silentbil/silent-bus/assets/10948399/5563225b-3588-4a6a-b61d-a4ff375aaa1c)
